name: STRT2_env
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - bedtools=2.29.2
  - fastqc=0.11.8
  - hisat2=2.1.0
  - multiqc=1.9
  - picard=2.20.4
  - samtools=1.10
  - stringtie=2.1.4
  - subread=2.0.0
  - ruby=2.6.6
